var message = "Help me, Kenobi. You're my only hope!";
console.log(message);
var episode = 4;
console.log("This is episode " + 4);
episode = episode + 1;
console.log("Next episode is " + episode);
var favoriteDroid;
favoriteDroid = "BB-8";
favoriteDroid = 10;
console.log("My favorite droid is " + favoriteDroid);
